### =========================================================================
### Extract junctions from genomic alignments
### -------------------------------------------------------------------------
###


setGeneric("junctions", function(x, ...) standardGeneric("junctions"))

setMethod("junctions", "GAlignments",
    function(x)
    {
        grl <- grglist(x, order.as.in.query=TRUE)
        psetdiff(granges(x), grl)
    }
)

setMethod("junctions", "GAlignmentPairs",
    function(x)
    {
        first_junctions <- junctions(x@first)
        last_junctions <- junctions(invertRleStrand(x@last))
        ## Fast way of doing mendoapply(c, first_junctions, last_junctions)
        ## on 2 CompressedList objects.
        ans <- c(first_junctions, last_junctions)
        collate_subscript <-
            IRanges:::make_XYZxyz_to_XxYyZz_subscript(length(x))
        ans <- ans[collate_subscript]
        ans <- shrinkByHalf(ans)
        mcols(ans) <- NULL
        ans
    }
)

setMethod("junctions", "GAlignmentsList",
    function(x, ignore.strand=FALSE)
    {
        if (!isTRUEorFALSE(ignore.strand))
            stop("'ignore.strand' must be TRUE or FALSE")
        if (ignore.strand)
            strand(x@unlistData) <- "*"
        grl <- junctions(x@unlistData)
        ans_breakpoints <- end(grl@partitioning)[end(x@partitioning)]
        ans_partitioning <- PartitioningByEnd(ans_breakpoints, names=names(x))
        relist(grl@unlistData, ans_partitioning)
    }
)


### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
### readTopHatJunctions()
###
### Read splice junctions file (junctions.bed) generated by the TopHat
### aligner into a GRanges object.
### Usage:
###   readTopHatJunctions("junctions.bed")
###
### Comparing with output of bed_to_juncs script (assuming the 'juncs.tab'
### file was obtained by passing 'junctions.bed' thru the bed_to_juncs):
###   junctions1 <- readTopHatJunctions("junctions.bed")
###   junctions2 <- readTopHatJunctions("juncs.tab",
###                                     file.is.bed_to_juncs.output=TRUE)
###   stopifnot(all(junctions1 == junctions2))
###

.tophatBedToJuncs <- function(x)
{
    if (!is(x, "GRanges"))
        stop("'x' must be a GRanges object")
    if (!identical(mcols(x)$thick, ranges(x)))
        stop("this BED file doesn't look like the junctions.bed file ",
             "generated by TopHat")
    blocks <- mcols(x)$blocks
    stopifnot(all(elementLengths(blocks) == 2L))
    unlisted_blocks <- unlist(blocks, use.names=FALSE)
    even_idx <- 2L * seq_along(x)
    odd_idx <- even_idx - 1L
    ans_start <- start(x) + end(unlisted_blocks)[odd_idx]
    ans_end <- start(x) + start(unlisted_blocks)[even_idx] - 2L
    ans <- GRanges(seqnames(x), IRanges(ans_start, ans_end), strand=strand(x))
    mcols(ans) <- DataFrame(name=mcols(x)$name,
                            score=as.integer(mcols(x)$score))
    ans
}

### 'file' must be the path or a connection object to a junctions.bed file as
### generated by TopHat, or to a tab-delimited file obtained by running
### TopHat's bed_to_juncs script on a junctions.bed file.
### Returns the junctions in a GRanges object.
### IMPORTANT NOTE: readTopHatJunctions() does NOT follow the convention used
### by TopHat that describes a junction by the position of the nucleotide
### immediately before and after the intron. In the GRanges object returned
### by readTopHatJunctions(), a junction is considered to start at the
### left-most and to end at the right-most nucleotide of the intron.
readTopHatJunctions <- function(file, file.is.bed_to_juncs.output=FALSE)
{
    if (!isTRUEorFALSE(file.is.bed_to_juncs.output))
        stop("'file.is.bed_to_juncs.output' must be TRUE or FALSE")
    if (is.character(file)) {
        if (!isSingleString(file))
            stop("'file' must be a single string")
        file_ext0 <- ".bed"
        file_ext <- substr(file, start=nchar(file) - nchar(file_ext0) + 1L,
                                 stop=nchar(file))
        if (file.is.bed_to_juncs.output) {
            if (file_ext == file_ext0)
                stop("'file.is.bed_to_juncs.output=TRUE' is not aimed to be ",
                     "used on a file\n  with the .bed extension")
            df <- read.table(file)
            ## The 2nd and 3rd columns in 'juncs.tab' are the left and right
            ## positions of the junctions, respectively. The convention used
            ## by TopHat is that these are NOT the positions of the left-most
            ## and right-most nucleotides of the intron, but rather the
            ## positions immediately before and after, respectively.
            ## Also these positions are *both* 0-based.
            ans_ranges <- IRanges(df[[2L]] + 2L, df[[3L]])
            ans <- GRanges(df[[1L]], ans_ranges, strand=df[[4L]])
            return(ans)
        }
        if (file_ext != file_ext0)
            warning("'file' has no .bed extension, suggesting it may not ",
                    "be a junctions.bed\n  file as generated by TopHat. ",
                    "I will assume it is this file anyway (or a BED\n  file ",
                    "with similar content). If 'file' is a tab-delimited ",
                    "file obtained\n  by running TopHat's bed_to_juncs script ",
                    "on a junctions.bed file, you\n  should use ",
                    "'file.is.bed_to_juncs.output=TRUE'")
    }
    junctions_bed <- rtracklayer::import(file)
    .tophatBedToJuncs(junctions_bed)
}


### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
### readSTARJunctions()
###
### Read splice junctions file (SJ.out.tab) produced by the STAR aligner
### into a GRanges object.
### Usage:
###   readSTARJunctions("SJ.out.tab")
###

readSTARJunctions <- function(file)
{
    df <- read.table(file)
    GRanges(df[[1L]],
            IRanges(df[[2L]], df[[3L]]),
            strand=strand(df[[4L]] == 2L),
            um_reads=df[[7L]],
            mm_reads=df[[8L]])
}


### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
### Old stuff (deprecated & defunct)
###

introns <- function(x)
{
    .Deprecated("junctions")
    junctions(x)
}

